# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
unordered_multichain_mode: true # When true, strict cross chain ordering of event processing will not be obeyed.
rollback_on_reorg: false
field_selection: # Additional fields available to index to augment data
  transaction_fields:
    - "hash"
    - "from"
contracts:
  - name: PoolManager
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 indexed id, uint256 amount)
      - event: Donate(bytes32 indexed id, address indexed sender, uint256 amount0, uint256 amount1)
      - event: Initialize(bytes32 indexed id, address indexed currency0, address indexed currency1, uint24 fee, int24 tickSpacing, address hooks, uint160 sqrtPriceX96, int24 tick)
      - event: ModifyLiquidity(bytes32 indexed id, address indexed sender, int24 tickLower, int24 tickUpper, int256 liquidityDelta, bytes32 salt)
      - event: OperatorSet(address indexed owner, address indexed operator, bool approved)
      - event: OwnershipTransferred(address indexed user, address indexed newOwner)
      - event: ProtocolFeeControllerUpdated(address indexed protocolFeeController)
      - event: ProtocolFeeUpdated(bytes32 indexed id, uint24 protocolFee)
      - event: Swap(bytes32 indexed id, address indexed sender, int128 amount0, int128 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick, uint24 fee)
      - event: Transfer(address caller, address indexed from, address indexed to, uint256 indexed id, uint256 amount)
  - name: PositionManager
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 indexed id)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event: Subscription(uint256 indexed tokenId, address indexed subscriber)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed id)
      - event: Unsubscription(uint256 indexed tokenId, address indexed subscriber)
networks:
  - id: 1301
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0xf969aee60879c54baaed9f3ed26147db216fd664
      - name: PoolManager
        address:
          - 0x00b036b58a818b1bc34d502d3fe730db729e62ac
